### ISSUE TITLE
Unexpected token '?'

### ISSUE THREAD

**Issue by bertearazvan** [rihr/cph-map#1]
Issue when trying to run the app locally. Please fix `webpack` configuration.

![9ac3b8aa618ad0da064690359aa5b0b4](https://user-images.githubusercontent.com/30385700/95741776-2c6b0580-0c8f-11eb-8102-cbd88aa349b5.png)

**Comment by rihr** [comment]
I believe the issue is that you're using a lower version of Node.js than 14, which may not support the nullish coalescing operator. Replacing it with the or (||) operator should fix it.
